module RPhonetic
  class RefinedSoundex < Encoder
    DEFAULT_MAPPING: String

    def initialize: (?mapping: String) -> void
    def self.encode: (String value, ?mapping: String) -> String
    def self.encode_many: (Array[String] values, ?mapping: String) -> Array[String]

    def difference: (String first, String second) -> Integer
  end
end
