# frozen_string_literal: true

module RPhonetic
  # Daitch–Mokotoff Soundex encodes names using caller-supplied rules.
  # Inherited {#encode} returns one nonbranching code; {#codes} returns all
  # branching six-digit codes. {#match?} compares the nonbranching codes.
  # Rules are parsed once and owned by the instance. No rules are bundled.
  #
  # @example
  #   encoder = RPhonetic::DaitchMokotoffSoundex.new(rules: File.read("config/dmrules.txt"))
  #   encoder.codes("Rosochowaciec")
  class DaitchMokotoffSoundex < Encoder
    # Parse rule text and create a reusable Daitch–Mokotoff encoder.
    # The rules must use the Apache Commons Codec rule format.
    #
    # @param rules [String] complete rule contents, not a file path
    # @param ascii_folding [Boolean] whether to apply the folding substitutions defined in the rules
    # @raise [RuleError] if rule parsing fails
    # @raise [TypeError] if rules is not a String
    # @raise [ArgumentError] if ascii_folding is not true or false
    # @raise [RuntimeError] if the upstream parser panics
    def initialize(rules:, ascii_folding: true)
      @native = NativeEncoder.daitch_mokotoff(text(rules), boolean(ascii_folding, :ascii_folding))
    end

    # Return all codes generated by branching rules.
    #
    # @param value [String] name to encode
    # @return [Array<String>] the distinct six-digit codes in upstream order
    # @raise [TypeError, ArgumentError, EncodingError, RuntimeError] for the same input or upstream errors as #encode
    def codes(value)
      @native.codes(text(value))
    end
  end
end
